import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";
import '../styles/Privacy.css';

const PrivacyPolicy = () => {
    return (
        <div className="privacy-policy-page">
            <Header />
            <main>
                <h1>Privacy Policy</h1>
                <p>Last updated: October 16, 2024</p>
                <p>
                    This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p>
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the 
                    <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer"> Privacy Policy Generator</a>.
                </p>

                <h2>Interpretation and Definitions</h2>
                <h3>Interpretation</h3>
                <p>
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>
                <h3>Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul>
                    <li>
                        <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
                    </li>
                    <li>
                        <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                    </li>
                    <li>
                        <strong>Application</strong> refers to AlgoQuiz, the software program provided by the Company.
                    </li>
                    <li>
                        <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AlgoQuiz.
                    </li>
                    <li>
                        <strong>Country</strong> refers to: Morocco.
                    </li>
                    <li>
                        <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                    </li>
                    <li>
                        <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
                    </li>
                    <li>
                        <strong>Service</strong> refers to the Application.
                    </li>
                    <li>
                        <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
                    </li>
                    <li>
                        <strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.
                    </li>
                    <li>
                        <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </li>
                    <li>
                        <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                    </li>
                </ul>

                <h2>Collecting and Using Your Personal Data</h2>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <ul>
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Usage Data</li>
                </ul>
                
                <h4>Usage Data</h4>
                <p>Usage Data is collected automatically when using the Service.</p>
                <p>
                    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p>
                    When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p>
                    We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                </p>

                <h4>Information from Third-Party Social Media Services</h4>
                <p>
                    The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:
                </p>
                <ul>
                    <li>Google</li>
                    <li>Facebook</li>
                    <li>Instagram</li>
                    <li>Twitter</li>
                    <li>LinkedIn</li>
                </ul>
                <p>
                    If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.
                </p>

                <h4>Information Collected while Using the Application</h4>
                <p>
                    While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
                </p>
                <ul>
                    <li>Information regarding your location</li>
                </ul>
                <p>
                    We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.
                </p>
                <p>You can enable or disable access to this information at any time, through Your Device settings.</p>

                <h3>Use of Your Personal Data</h3>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul>
                    <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                    <li><strong>For the performance of a contract:</strong> the development, compliance, and undertaking of the purchase contract for the products, items, or services You have purchased or any other contract with Us.</li>
                    <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other electronic communication regarding updates or informative communications.</li>
                    <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services, and events.</li>
                    <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                    <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, or similar proceeding.</li>
                    <li><strong>For other purposes</strong>: We may use Your information for data analysis, identifying usage trends, and improving our Service.</li>
                </ul>

                <h3>Retention of Your Personal Data</h3>
                <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>
                <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when it is used to strengthen security or improve functionality.</p>

                <h3>Transfer of Your Personal Data</h3>
                <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located.</p>
                <p>Your consent to this Privacy Policy represents Your agreement to that transfer.</p>

                <h3>Delete Your Personal Data</h3>
                <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>

                <h3>Disclosure of Your Personal Data</h3>
                <h4>Business Transactions</h4>
                <p>If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred.</p>

                <h4>Law enforcement</h4>
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data.</p>

                <h4>Other legal requirements</h4>
                <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
                <ul>
                    <li>Comply with a legal obligation</li>
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing</li>
                    <li>Protect the personal safety of Users of the Service</li>
                    <li>Protect against legal liability</li>
                </ul>

                <h3>Security of Your Personal Data</h3>
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet is 100% secure.</p>

                <h2>Children's Privacy</h2>
                <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.</p>

                <h2>Links to Other Websites</h2>
                <p>Our Service may contain links to other websites that are not operated by Us. We have no control over and assume no responsibility for the content or privacy policies of any third-party sites.</p>

                <h2>Changes to this Privacy Policy</h2>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

                <h2>Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul>
                    <li>By email: mrelyazidi.omar@gmail.com</li>
                    <li>By email: maryembenhaida9@gmail.com</li>
                    <li>By visiting this page on our website: <a href="https://github.com/OMARTK1/algoquiz" target="_blank" rel="noopener noreferrer">https://github.com/OMARTK1/algoquiz</a> or <a href="https://github.com/Mery9yuka" rel="external nofollow noopener" target="_blank">https://github.com/Mery9yuka</a></li>
                </ul>
            </main>
            <Footer />
        </div>
    );
};

export default PrivacyPolicy;